---
#
# NVIDIA GPU Operator
#
- name: Add NVIDIA helm repository
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: "https://nvidia.github.io/gpu-operator"

- name: Install GPU Operator
  kubernetes.core.helm:
    name: gpu-operator
    chart_ref: nvidia/gpu-operator
    release_namespace: gpu-operator
    create_namespace: true
    values:
      nfd:
        enabled: true
      mig:
        strategy: single
      driver:
        enabled: false
        rdma:
          enabled: true
          useHostMofed: true 
      toolkit:
        enabled: false
      migManager:
        enabled: true
