---
#
# MPI Operator
#
- name: Download MPI operator
  git:
    repo: https://github.com/kubeflow/mpi-operator
    dest: /home/mdxuser/mpi-operator
    force: yes

- name: Install MPI operator
  k8s:
    state: present
    src: /home/mdxuser/mpi-operator/deploy/v2beta1/mpi-operator.yaml
