---
#
# Prometheus (Grafana) Oeprator
#
- name: Add prometheus helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Install prometheus stack
  kubernetes.core.helm:
    name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: prometheus
    create_namespace: true
