---
- name: Common configuration
  hosts: all
  roles: 
    - common
  tags:
  - common
  - all
  - never

- name: Install harbor container registry
  hosts: registry
  vars_files:
    - vault.yaml
  # vars_prompt:
  #   - name: harbor_admin_password
  #     prompt: Enter admin password for harbor
  #     private: yes
  #     default: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=20') }}"
  #   - name: harbor_db_password
  #     prompt: Enter database password for harbor
  #     private: yes
  #     default: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=20') }}"
  roles:
    - registry
  tags:
  - registry
  - all
  - never

- name: Install kubernets cluster
  hosts: bastion_host
  roles:
    - k8s
  tags:
  - k8s_base
  - k8s
  - all
  - never

- name: Setup kubernets workers
  hosts: kube_worker
  roles:
    - k8s_worker
  tags:
  - k8s_worker
  - k8s
  - all
  - never

- name: Setup kubernetes gpu workers
  hosts: kube_gpu
  roles:
    - k8s_gpu
  tags:
  - k8s_gpu
  - k8s
  - all
  - never

- name: Deploy kubernetes services
  hosts: bastion_host
  vars_files:
    - vault.yaml
  # vars_prompt:
  #   - name: grafana_password
  #     prompt: Enter grafana password
  #     private: yes
  #     default: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=20') }}"
  roles:
    - k8s_service
  tags:
  - service
  - k8s
  - all
  - never
