---
harbor_version: 2.4.2

harbor_dir: '{{ mdxuser_home }}/harbor'
harbor_cert_dir: '{{ harbor_dir }}/cert'
harbor_data_dir: '{{ harbor_dir }}/data'

ca_subject: '/C=JP/ST=Chiba/L=Kashiwa/O=MDX/OU=Private/CN={{ registry_server }}'
server_subject: '/C=JP/ST=Chiba/L=Kashiwa/O=MDX/OU=Private/CN={{ registry_server }}'
