apiVersion: v1
kind: Pod
metadata:
  name: exascaler-pod-fast
spec:
  #securityContext:
  #  runAsUser: 1000
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /fast
          name: exascaler-data
  volumes:
    - name: exascaler-data
      persistentVolumeClaim:
        claimName: exascaler-pvc-fast
        readOnly: false
