---
- name: Resolve build dependencies
  apt:
    name: '{{ item }}'
  become: yes
  loop:
    - build-essential
    - devscripts
    - debhelper
    - check
    - libsubunit-dev
    - fakeroot
    - pkg-config
    - dkms


- name: Download GDRCopy
  get_url:
    url: https://github.com/NVIDIA/gdrcopy/archive/refs/tags/v{{ gdr_version }}.tar.gz
    dest: /tmp/gdrcopy-{{ gdr_version }}.tar.gz

- name: Unarchive GDRCopy
  unarchive:
    src: /tmp/gdrcopy-{{ gdr_version }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: Building GDRCopy
  shell:
    cmd: CUDA=/usr ./build-deb-packages.sh
    chdir: /tmp/gdrcopy-{{ gdr_version }}/packages

- name: Install GDRCopy
  command:
    cmd: 'dpkg -i {{ item }}'
    chdir: /tmp/gdrcopy-2.3/packages
  become: yes
  loop:
    - gdrdrv-dkms_{{ gdr_version_minor }}_amd64.Ubuntu20_04.deb
    - libgdrapi_{{ gdr_version_minor}}_amd64.Ubuntu20_04.deb
    - gdrcopy-tests_{{ gdr_version_minor }}_amd64.Ubuntu20_04.deb  
    - gdrcopy_{{ gdr_version_minor }}_amd64.Ubuntu20_04.deb        
