---
#
# Install the certificates for private registry
#
- name: Install private certificate
  copy:
    src: '{{ mdxuser_home }}/{{ registry_server }}.crt'
    dest: /etc/ssl/certs/
  become: yes

- name: Create cert directory
  file: 
    path: /etc/containerd/certs.d/{{ registry_server }}
    state: directory
  become: yes

- name: Install hosts.toml
  copy:
    dest: /etc/containerd/certs.d/{{ registry_server }}/hosts.toml
    content: |
      server = "https://{{ registry_server }}"
      
      [host."https://{{ registry_server }}"]
        capabilities = ["pull", "resolve"]
        ca = "/etc/ssl/certs/{{ registry_server }}.crt"
  become: yes

